
[French_government_news]
entrySelector = "div.tile"
linkSelector = "a.fr-card__link"
title = "Toute l'actualitÃ© | Gouvernement.fr"
titleSelector = "a.fr-card__link"
url = "https://www.gouvernement.fr/toute-l-actualite"

[electricity_map]
entrySelector = "div.date > div.w-dyn-item"
imageSelector = "img.image-11"
linkSelector = "a.text-small"
title = "Blog - Electricity Maps"
titleSelector = "h2.heading-20"
url = "https://www.electricitymaps.com/blog"

[jancovici]
entrySelector = "article.relative"
linkSelector = "*"
title = "Posts LinkedIn Jean-Marc Jancovici"
titleSelector = "a.leading-open"
url = ["https://fr.linkedin.com/posts/jean-marc-jancovici_il-ny-a-pas-que-notre-premier-ministre-qui-activity-7325157033358385154-_v8w","https://fr.linkedin.com/posts/jean-marc-jancovici_notre-syst%C3%A8me-%C3%A9lectrique-est-en-train-de-activity-7324734616085422080-Kjix","https://fr.linkedin.com/posts/jean-marc-jancovici_l%C3%A9quivalent-en-plus-gros-anglais-du-haut-activity-7323384763086422017-dFut","https://fr.linkedin.com/posts/jean-marc-jancovici_donald-trump-est-le-plus-r%C3%A9volutionnaire-activity-7323658169354752001-Q4Md","https://fr.linkedin.com/posts/jean-marc-jancovici_a-loccasion-de-la-sortie-du-monde-sans-fin-activity-7323955807820079104-YBce"]

[luisant]
entrySelector = "td.mdl-data-table__cell--non-numeric > ul > li"
linkSelector = "a"
title = "Luisant - Saison culturelle"
titleSelector = "a"
url = "https://www.luisant.fr/decouvrir-bouger/culture-et-loisirs/saison-culturelle"
