
[French_government_news]
entrySelector = "div.tile"
linkSelector = "a.fr-card__link"
title = "Toute l'actualitÃ© | Gouvernement.fr"
titleSelector = "a.fr-card__link"
url = "https://www.gouvernement.fr/toute-l-actualite"

[electricity_map]
entrySelector = "div.date > div.w-dyn-item"
imageSelector = "img.image-11"
linkSelector = "a.text-small"
title = "Blog - Electricity Maps"
titleSelector = "h2.heading-20"
url = "https://www.electricitymaps.com/blog"

[jancovici]
entrySelector = "article.relative"
linkSelector = "*"
title = "Posts LinkedIn Jean-Marc Jancovici"
titleSelector = "a.leading-open"
url = ["https://fr.linkedin.com/posts/jean-marc-jancovici_la-d%C3%A9carbonation-de-l%C3%A9conomie-va-%C3%AAtre-un-activity-7335758533440729089-iuUV","https://fr.linkedin.com/posts/jean-marc-jancovici_le-textile-comme-le-reste-de-nos-produits-activity-7335311071160815616-a5F_","https://fr.linkedin.com/posts/jean-marc-jancovici_qui-a-dit-la-nature-fournit-des-services-activity-7334891802950340609-BF_8"]

[luisant]
entrySelector = "td.mdl-data-table__cell--non-numeric > ul > li"
linkSelector = "a"
title = "Luisant - Saison culturelle"
titleSelector = "a"
url = "https://www.luisant.fr/decouvrir-bouger/culture-et-loisirs/saison-culturelle"
